import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const requireDemo = createRequire(join(root, "static", "package.json"));
const { build } = requireDemo("esbuild");
const bundled = await build({ entryPoints: [join(root, "lib", "demo-store.ts")], bundle: true, write: false, platform: "node", format: "esm", nodePaths: [join(root, "static", "node_modules")] });
const { createDemoStore } = await import(`data:text/javascript;base64,${Buffer.from(bundled.outputFiles[0].text).toString("base64")}`);
const records = new Map();
const storage = { getItem: key => records.get(key) ?? null, setItem: (key, value) => records.set(key, value), removeItem: key => records.delete(key) };
const store = createDemoStore(storage);
const post = body => store.transport("/api/coordination", { method: "POST", body: JSON.stringify(body) });
const fields = { organization: "Test Clinic", location: "Asheville", region: "North Carolina", item: "Trauma kits", quantity: 20 };
const initial = store.read();
assert.equal((await post({ action: "request", ...fields, quantity: 0, priority: "High" })).status, 400);
assert.equal((await post({ action: "request", ...fields, quantity: 1.5, priority: "High" })).status, 400);
assert.equal((await post({ action: "request", ...fields, priority: "High" })).status, 200);
assert.equal((await post({ action: "supply", ...fields, organization: "Test Donor" })).status, 200);
let data = store.read();
const requestId = data.requests[0].id;
const supplyId = data.supplies[0].id;
const allocation = { action: "allocate", requestId, supplyId, quantity: 20 };
const results = await Promise.all([post(allocation), post(allocation)]);
assert.deepEqual(results.map(result => result.status).sort(), [200, 400]);
data = store.read();
const id = data.shipments[0].id;
assert.equal((await post({ action: "status", id, status: "Delivered" })).status, 400);
assert.equal((await post({ action: "status", id, status: "In transit" })).status, 200);
assert.equal((await post({ action: "status", id, status: "Delivered" })).status, 200);
assert.equal(createDemoStore(storage).read().shipments[0].status, "Delivered");
store.reset();
assert.deepEqual(store.read(), initial);
const blocked = createDemoStore({ ...storage, setItem() { throw new Error("Storage blocked"); } });
assert.equal((await blocked.transport("/api/coordination", { method: "POST", body: JSON.stringify({ action: "supply", ...fields }) })).status, 400);
console.log("Demo checks passed: validation, allocation limits, ordered shipment status, persistence, reset and storage failure.");
